server:
  port: 80

spring:
  application:
    name: cloud-consumer-order80
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    druid:
      url: jdbc:mysql://127.0.0.1:3306/humc?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      initial-size: 1
      validation-query: SELECT 1
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.humc.springcloud.entities