server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    druid:
      url: jdbc:mysql://127.0.0.1:3306/humc?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: mysql
      initial-size: 1
      validation-query: SELECT 1
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.humc.springcloud.entities