server:
  port: 8001

spring:
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    druid:
      url: jdbc:mysql://127.0.0.1:3306/humc?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: mysql
      initial-size: 1
      validation-query: SELECT 1
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/
      #单机版
      # defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: payment8001
    prefer-ip-address: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.humc.springcloud.entities